name: Deploy

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - env:
          CERT: ${{ secrets.DB_CERT }}
          CONFIG: ${{ secrets.OKTETO_CONFIG }}
        run: |
          echo -n "$CERT" | base64 --decode > cc-ca.crt
          echo -n "$CONFIG" | base64 --decode > okteto-kube.config
      - uses: okteto/namespace@master
        with:
          namespace: table-top-games
      - uses: okteto/deploy-stack@master
        env: 
          KUBECONFIG: ./okteto-kube.config