name: Deploy

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - env:
          CERT: ${{ secrets.DB_CERT }}
        run: echo -n "$CERT" | base64 --decode > cc-ca.crt
      - uses: okteto/deploy-stack@master